[package]
name = "pacgrep"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
regex = "1.10.5"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
anyhow = "1.0.86"
walkdir = "2.5.0"
